# See here for image contents: https://github.com/devcontainers/images/tree/main/src/rust
FROM mcr.microsoft.com/devcontainers/rust:1

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
